spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/bank
    username: user
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


backendbankclientprogram:
  app:
    secret: YtK3cKn0clKHH3ZCDlQCyBBiKUOD2klKvtSp+lLUQ7I=
    expirationMs: 3600000
